DEFAULT_EMAIL = "jay.design.developer@gmail.com"
DEFAULT_PASS = "9000060553Vinay$"
DEFAULT_TOKEN = "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"
PDF_FOLDER_PATH = "./pdf_folder"
CHROMA_DB_PATH = "./chroma_db"

